name: The Quick Brown Fox
favicon: null
layout_spectrum: 0.93723
typography_spectrum: 0.0559
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0c0d'
    - '#f1e1e2'
    - '#668542'
    - '#5c5044'
    - '#bdb2b1'
  brandStrength: 0.4375
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
